name: homeassistant_ws
description: A dart package to connect to Home Assistant via WebSockets.
version: 1.0.0
# repository: https://github.com/koproductions-code/homeassistant_ws

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^2.4.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter:
    sdk: flutter
  provider: ^6.1.2